### ISSUE TITLE
could not get the example to work as expected

### ISSUE THREAD

**Issue by kjellkvinge** [etienne-napoleone/chalk#3]
Hi. Just wanted to try vlang, and of course I needed colors for my terminal :)

I tried to install as described in readme, which works fine. The code is downloaded to  `~/.vmodules/etienne-napoleone`

So i guess a working example should be
```
import etienne-napoleone.chalk
...
```

But this gives me the following warning:

    cannot import module "etienne" (not found)

So, the "dash" in your username is probably not compatible with the way V imports libraries.
When I rename this folder to "etiennenapoleone", it works fine.

Thank you.

**Comment by etienne-napoleone** [comment]
Hey! Thanks for notifying me!
I opened an issue on the vlang repository https://github.com/vlang/v/issues/3467 .
Imo it doesn't make sense to have a packet manager relying on github usernames if it actually can't handle a big bunch of them.
Btw this package needs to be updated to use a struct to expose a better api. You probably want to check https://vpm.best/mod/thecodrr.crayon out !

**Comment by etienne-napoleone** [comment]
fixed in https://github.com/vlang/v/issues/3467
