### ISSUE TITLE
Feature request: hex color

### ISSUE THREAD

**Issue by depperm** [etienne-napoleone/chalk#5]
I was about to create my own chalk module that allowed hex, but then I saw this. It would only require a bit more work I think to expand this:

This is the syntax for rgb value:
```
//bg
println('\e[48;2;$r;$g;${b}mhello world\e[0m')
//fg
println('\e[38;2;$r;$g;${b}mhello world\e[0m')
```
converting hex (`#ffffff`) to rgb
```
import strconv

fn rgb_from_hex (s string) string {
    r := strconv.common_parse_int(s[1..3], 16, 16, true, false) or { 0 }
    g := strconv.common_parse_int(s[3..5], 16, 16, true, false) or { 0 }
    b := strconv.common_parse_int(s[5..7], 16, 16, true, false) or { 0 }
    return '$r;$g;$b'
}
```

**Comment by etienne-napoleone** [comment]
Please check out @Mewzax fork: [Mewzax/chalk](https://github.com/Mewzax/chalk), he implemented that and will probably keep it more up to date than this repo
